# Generated by Django 5.2.6 on 2025-09-16 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('kPads', 'Knee Pads')], default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
