# Generated by Django 5.2.6 on 2025-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('gloves', 'Gloves'), ('kPads', 'Knee Pads')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
