# Generated by Django 5.2.6 on 2025-09-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_rename_news_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='personal',
            new_name='persona',
        ),
    ]
