# Generated by Django 5.2.6 on 2025-09-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_personal_employee_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
